
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: prom-storage-pvc
spec:
  storageClassName: gp2
  accessModes:
  
ReadWriteOnce
resources:
  requests:
    storage: 10Gi